language: csharp
solution: MonoMyst.sln
mono: latest
dotnet: latest

before_install:
  - sudo apt-get install unzip

script:
  - dotnet restore
  - dotnet build

after_success:
  - bash ./ReleaseDocs.sh
