name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Build Docs
      uses: nikeee/docfx-action@v0.1.0
      with:
        args: docs/docfx.json
    - name: Publish gh-pages
      uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}
